routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');

Route::get('search/', 'PageController@search');
Route::resource('/kota', 'KotaController');
Route::resource('/provinsi', 'ProvinsiController');
Route::resource('/bus', 'BusController');
Route::resource('/route', 'RouteController');

app/Provinsi.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Provinsi extends Model
{
    protected $table = 'provinsi';
    protected $fillable = [
        'id', 'provinsi_name', 'created_at', 'created_by', 'updated_at', 'updated_by',
    ];

    public function kota()
    {
    	return $this->hasMany("App\Kota");
    }
}

app/Http/Controllers/ProvinsiController.php
<?php

namespace App\Http\Controllers;

use App\Provinsi;
use Illuminate\Http\Request;

class ProvinsiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $provinsi = Provinsi::orderBy('id', 'DESC')->paginate(5);

        return view('provinsi.index', compact('provinsi'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('provinsi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'provinsi_name' => 'required',
        ]);

        $provinsi = Provinsi::create($request->all());

        return redirect()->route('provinsi.index')->with('message', 'Provinsi berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $provinsi = Provinsi::findOrFail($id);
        return view('provinsi.show', compact('provinsi'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $provinsi = Provinsi::findOrFail($id);
        return view('provinsi.edit', compact('provinsi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
            'provinsi_name' => 'required'
        ]);

        $provinsi = Provinsi::findOrFail($id)->update($request->all());

        return redirect()->route('provinsi.index')->with('message', 'Provinsi berhasil diubah!');
    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $provinsi = Provinsi::findOrFail($id)->delete();
        return redirect()->route('provinsi.index')->with('message', 'Provinsi berhasil dihapus!');
   
    }
}

resources/views/provinsi/create.blade.php
@extends('layouts.app')

@section('content')
<h4>Provinsi Baru</h4> 
<form action="{{ route('provinsi.store') }}" method="post">
    {{csrf_field()}}
    <div class="form-group row {{ $errors->has('provinsi_name') ? 'has-error' : '' }}">
        <label for="title" class="col-sm-2 col-form-label">Nama Provinsi</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="provinsi_name" placeholder="Nama Provinsi">
        </div>
        @if ($errors->has('provinsi_name'))
            <span class="help-block">{{ $errors->first('provinsi_name') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('provinsi.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/provinsi/edit.blade.php
@extends('layouts.app')

@section('content')
<h4>Ubah Provinsi</h4>
<form action="{{ route('provinsi.update', $provinsi->id) }}" method="post">
    {{csrf_field()}}
    {{ method_field('PUT') }}
    <div class="form-group row {{ $errors->has('provinsi_name') ? 'has-error' : '' }}">
        <label for="provinsi_name" class="col-sm-2 col-form-label">Nama Provinsi</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="provinsi_name" placeholder="Nama Provinsi" value="{{ $provinsi->provinsi_name }}">
        </div>
        @if ($errors->has('provinsi_name'))
            <span class="help-block">{{ $errors->first('provinsi_name') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('provinsi.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/provinsi/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('provinsi.create') }}" class="btn btn-info btn-sm">Provinsi Baru</a>
    
    @if ($message = Session::get('message'))
        <div class="alert alert-success martop-sm">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-responsive martop-sm">
        <thead>
            <th>ID</th>
            <th>Nama Provinsi</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach ($provinsi as $provinsiWilayah)
                <tr>
                    <td>{{ $provinsiWilayah->id }}</td>
                    <td><a href="{{ route('provinsi.show', $provinsiWilayah->id) }}">{{ $provinsiWilayah->provinsi_name }}</a></td>
                    <td>
                        <form action="{{ route('provinsi.destroy', $provinsiWilayah->id) }}" method="post">
                            {{csrf_field()}}
                            {{ method_field('DELETE') }}
                            <a href="{{ route('provinsi.edit', $provinsiWilayah->id) }}" class="btn btn-warning btn-sm">Ubah</a>
                            <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/provinsi/show.blade.php
@extends('layouts.app')

@section('content')
<h4>{{ $provinsi->provinsi_name }}</h4>
<a href="{{ route('provinsi.index') }}" class="btn btn-default">Kembali</a>
@endsection