routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');

Route::get('search/', 'PageController@search');
Route::resource('/kota', 'KotaController');
Route::resource('/provinsi', 'ProvinsiController');
Route::resource('/bus', 'BusController');
Route::resource('/route', 'RouteController');

app/Bus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bus extends Model
{
    protected $table = 'bus';
    protected $fillable = [
        'id', 'bus_type_id', 'bus_class_id', 'bus_name', 'bus_code', 'created_at', 'created_by', 'updated_at', 'updated_by',
    ];

    public function busType()
    {
    	return $this->belongsTo("App\BusType");
    }

    public function busClass()
    {
    	return $this->hasOne("App\BusClass");
    }

    public function Route()
    {
    	return $this->hasMany("App\Route");
    }
}

app/BusType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BusType extends Model
{
    protected $table = 'bus_type';
    protected $fillable = [
        'id', 'bus_type_name', 'created_at', 'created_by', 'updated_at', 'updated_by',
    ];

    public function bus()
    {
    	returm $this->hasMany("App\Bus");
    }
}

app/Http/Controllers/BusController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BusController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/bus/create.blade.php
@extends('layouts.app')

@section('content')
<h4>bus Baru</h4>
<form action="{{ route('bus.store') }}" method="post">
    {{csrf_field()}}
    <div class="form-group row {{ $errors->has('bus_name') ? 'has-error' : '' }}">
        <label for="title" class="col-sm-2 col-form-label">Nama bus</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="bus_name" placeholder="Nama bus">
        </div>
        @if ($errors->has('bus_name'))
            <span class="help-block">{{ $errors->first('bus_name') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('bus.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/bus/edit.blade.php
@extends('layouts.app')

@section('content')
<h4>Ubah bus</h4>
<form action="{{ route('bus.update', $bus->id) }}" method="post">
    {{csrf_field()}}
    {{ method_field('PUT') }}
    <div class="form-group row {{ $errors->has('bus_name') ? 'has-error' : '' }}">
        <label for="bus_name" class="col-sm-2 col-form-label">Nama bus</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="bus_name" placeholder="Nama bus" value="{{ $bus->bus_name }}">
        </div>
        @if ($errors->has('bus_name'))
            <span class="help-block">{{ $errors->first('bus_name') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('bus.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/bus/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('bus.create') }}" class="btn btn-info btn-sm">bus Baru</a>
    
    @if ($message = Session::get('message'))
        <div class="alert alert-success martop-sm">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-responsive martop-sm">
        <thead>
            <th>ID</th>
            <th>Nama bus</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach ($bus as $busWilayah)
                <tr>
                    <td>{{ $busWilayah->id }}</td>
                    <td><a href="{{ route('bus.show', $busWilayah->id) }}">{{ $busWilayah->bus_name }}</a></td>
                    <td>
                        <form action="{{ route('bus.destroy', $busWilayah->id) }}" method="post">
                            {{csrf_field()}}
                            {{ method_field('DELETE') }}
                            <a href="{{ route('bus.edit', $busWilayah->id) }}" class="btn btn-warning btn-sm">Ubah</a>
                            <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/bus/show.blade.php
@extends('layouts.app')

@section('content')
<h4>{{ $bus->bus_name }}</h4>
<a href="{{ route('bus.index') }}" class="btn btn-default">Kembali</a>
@endsection