routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');

Route::get('search/', 'PageController@search');
Route::resource('/kota', 'KotaController');
Route::resource('/provinsi', 'ProvinsiController');
Route::resource('/bus', 'BusController');
Route::resource('/route', 'RouteController');

app/Kota.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kota extends Model
{
    protected $table = 'kota';
    protected $fillable = [
        'id', 'provinsi_id', 'kota_nama', 'kode_kota', 'created_at', 'created_by', 'updated_at', 'updated_by',
    ];

    public function provinsi()
    {
    	return $this->belongsTo("App\Provinsi");
    }
}

app/Http/Controllers/KotaController.php
<?php

namespace App\Http\Controllers;

use App\Kota;
use App\Provinsi;
use Illuminate\Http\Request;

class KotaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
        $kota = Kota::orderBy('id', 'DESC')->with("provinsi")->paginate(5);
        return view('kota.index', compact('kota'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $provinsi = Provinsi::orderBy('provinsi_name', 'ASC')->get();
        return view('kota.create', compact('provinsi'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'kode_kota' => 'required',
            'provinsi_id' => 'required',
            'kota_nama' => 'required',
        ]);

        $kota = Kota::create($request->all());

        return redirect()->route('kota.index')->with('message', 'Kota berhasil dibuat!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $kota = Kota::with('provinsi')->findOrFail($id);

        return view('kota.show', compact('kota'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $kota = Kota::findOrFail($id);
        $provinsi = Provinsi::orderBy('provinsi_name', 'ASC')->get();
        return view('kota.edit', compact('kota', 'provinsi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
            'kota_nama' => 'required'
        ]);

        $kota = Kota::findOrFail($id)->update($request->all());

        return redirect()->route('kota.index')->with('message', 'kota berhasil diubah!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $kota = Kota::findOrFail($id)->delete();
        return redirect()->route('kota.index')->with('message', 'kota berhasil dihapus!');
    }
}

resources/views/kota/create.blade.php
@extends('layouts.app')

@section('content')
<h4>Kota Baru</h4>
<form action="{{ route('kota.store') }}" method="post">
    {{csrf_field()}}
    <div class="form-group row {{ $errors->has('kode_kota') ? 'has-error' : '' }}">
        <label for="kode_kota" class="col-sm-2 col-form-label">Kode Kota*</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="kode_kota" placeholder="Kode Kota" required="">
        </div>
        @if ($errors->has('kode_kota'))
            <span class="help-block">{{ $errors->first('kode_kota') }}</span>
        @endif
    </div>
    <div class="form-group row {{ $errors->has('id') ? 'has-error' : '' }}">
        <label for="id" class="col-sm-2 col-form-label">Name Provinsi</label>
        <div class="col-sm-4">
            <select class="form-control" name="provinsi_id">
                @foreach ($provinsi as $provinsiWilayah)
                    <option value="{{ $provinsiWilayah->id }}">{{ $provinsiWilayah->provinsi_name }} </option>
                @endforeach
            </select>
        </div>
        @if ($errors->has('provinsi_id'))
            <span class="help-block">{{ $errors->first('provinsi_id') }}</span>
        @endif
    </div>
    <div class="form-group row {{ $errors->has('kota_nama') ? 'has-error' : '' }}">
        <label for="title" class="col-sm-2 col-form-label">Nama kota</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="kota_nama" placeholder="Nama kota">
        </div>
        @if ($errors->has('kota_nama'))
            <span class="help-block">{{ $errors->first('kota_nama') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('kota.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/kota/edit.blade.php
@extends('layouts.app')

@section('content')
<h4>Ubah kota</h4>
<form action="{{ route('kota.update', $kota->id) }}" method="post">
    {{csrf_field()}}
    {{ method_field('PUT') }}
    <div class="form-group row {{ $errors->has('kode_kota') ? 'has-error' : '' }}">
        <label for="kode_kota" class="col-sm-2 col-form-label">Kode Kota*</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="kode_kota" placeholder="Kode Kota" value="{{ $kota->kode_kota }}" required="">
        </div>
        @if ($errors->has('kode_kota'))
            <span class="help-block">{{ $errors->first('kode_kota') }}</span>
        @endif
    </div>
    <div class="form-group row {{ $errors->has('id') ? 'has-error' : '' }}">
        <label for="id" class="col-sm-2 col-form-label">Name Provinsi</label>
        <div class="col-sm-4">
            <select class="form-control" name="provinsi_id">
                @foreach ($provinsi as $provinsiWilayah)
                    @if ($kota->provinsi_id == $provinsiWilayah->id)
                        <option value="{{ $provinsiWilayah->id }}" selected>{{ $provinsiWilayah->provinsi_name }} </option>
                    @else
                        <option value="{{ $provinsiWilayah->id }}">{{ $provinsiWilayah->provinsi_name }} </option>
                    @endif

                @endforeach
            </select>
        </div>
        @if ($errors->has('id'))
            <span class="help-block">{{ $errors->first('id') }}</span>
        @endif
    </div>
    <div class="form-group row {{ $errors->has('kota_nama') ? 'has-error' : '' }}">
        <label for="title" class="col-sm-2 col-form-label">Nama kota</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="kota_nama" placeholder="Nama kota" value="{{ $kota->kota_nama }}">
        </div>
        @if ($errors->has('kota_nama'))
            <span class="help-block">{{ $errors->first('kota_nama') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('kota.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/kota/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('kota.create') }}" class="btn btn-info btn-sm">Kota Baru</a>
    
    @if ($message = Session::get('message'))
        <div class="alert alert-success martop-sm">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-responsive martop-sm">
        <thead>
            <th>ID</th>
            <th>Nama Provinsi</th>
            <th>Nama Kota</th>
            <th>Kode Kota</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach ($kota as $kotaWilayah)
                <tr>
                    <td>{{ $kotaWilayah->id }}</td>
                    <td>{{ $kotaWilayah->provinsi->provinsi_name }}</td>
                    <td><a href="{{ route('kota.show', $kotaWilayah->id) }}">{{ $kotaWilayah->kota_nama }}</a></td>
                    <td>{{ $kotaWilayah->kode_kota }}</td>
                    <td>
                        <form action="{{ route('kota.destroy', $kotaWilayah->id) }}" method="post">
                            {{csrf_field()}}
                            {{ method_field('DELETE') }}
                            <a href="{{ route('kota.edit', $kotaWilayah->id) }}" class="btn btn-warning btn-sm">Ubah</a>
                            <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/kota/show.blade.php
@extends('layouts.app')

@section('content')
<h5>{{ $kota->provinsi->provinsi_name }}</h5>
<h4>{{ $kota->kota_nama }}</h4>
<a href="{{ route('kota.index') }}" class="btn btn-default">Kembali</a>
@endsection