routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PageController@index');

Route::get('search/', 'PageController@search');
Route::resource('/kota', 'KotaController');
Route::resource('/provinsi', 'ProvinsiController');
Route::resource('/bus', 'BusController');
Route::resource('/route', 'RouteController');

app/Route.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Route extends Model
{
	protected $table = 'route';
    protected $fillable = [
        'id', 'bus_id', 'route_city_fron', 'route_city_to', 'take_off_time', 'arrive_time', 'price', 'created_at', 'created_by', 'updated_at', 'updated_by',
    ];

    public function bus()
    {
    	return $this->belongsTo("App\Bus");
    }
}

app/Http/Controllers/RouteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class RouteController extends Controller
{ 
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/route/create.blade.php
@extends('layouts.app')

@section('content')
<h4>route Baru</h4>
<form action="{{ route('route.store') }}" method="post">
    {{csrf_field()}}
    <div class="form-group row {{ $errors->has('route_name') ? 'has-error' : '' }}">
        <label for="title" class="col-sm-2 col-form-label">Nama route</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="route_name" placeholder="Nama route">
        </div>
        @if ($errors->has('route_name'))
            <span class="help-block">{{ $errors->first('route_name') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('route.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/route/edit.blade.php
@extends('layouts.app')

@section('content')
<h4>Ubah route</h4>
<form action="{{ route('route.update', $route->id) }}" method="post">
    {{csrf_field()}}
    {{ method_field('PUT') }}
    <div class="form-group row {{ $errors->has('route_name') ? 'has-error' : '' }}">
        <label for="route_name" class="col-sm-2 col-form-label">Nama route</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" name="route_name" placeholder="Nama route" value="{{ $route->route_name }}">
        </div>
        @if ($errors->has('route_name'))
            <span class="help-block">{{ $errors->first('route_name') }}</span>
        @endif
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-info">Simpan</button>
        <a href="{{ route('route.index') }}" class="btn btn-default">Kembali</a>
    </div>
</form>
@endsection

resources/views/route/index.blade.php
@extends('layouts.app')

@section('content')
    <a href="{{ route('route.create') }}" class="btn btn-info btn-sm">route Baru</a>
    
    @if ($message = Session::get('message'))
        <div class="alert alert-success martop-sm">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-responsive martop-sm">
        <thead>
            <th>ID</th>
            <th>Nama route</th>
            <th>Action</th>
        </thead>
        <tbody>
            @foreach ($route as $routeWilayah)
                <tr>
                    <td>{{ $routeWilayah->id }}</td>
                    <td><a href="{{ route('route.show', $routeWilayah->id) }}">{{ $routeWilayah->route_name }}</a></td>
                    <td>
                        <form action="{{ route('route.destroy', $routeWilayah->id) }}" method="post">
                            {{csrf_field()}}
                            {{ method_field('DELETE') }}
                            <a href="{{ route('route.edit', $routeWilayah->id) }}" class="btn btn-warning btn-sm">Ubah</a>
                            <button type="submit" class="btn btn-danger btn-sm">Hapus</button>
                        </form>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection

resources/views/route/show.blade.php
@extends('layouts.app')

@section('content')
<h4>{{ $route->route_name }}</h4>
<a href="{{ route('route.index') }}" class="btn btn-default">Kembali</a>
@endsection